// swift-tools-version: 6.0

import PackageDescription

/// The echno-ios package.
///
/// Two targets, and the direction of dependency between them is the whole design:
///
/// - `EchnoAPI` is generated by swift-openapi-generator from the backend's own
///   OpenAPI document, vendored by `Scripts/sync-openapi.sh`. Never hand-edited.
/// - `EchnoKit` is hand-written: domain types, the mapping that turns generated
///   DTOs into them, service actors, observable stores, and auth.
///
/// This app talks to the Spring Boot backend directly. It does **not** depend on
/// `@tornotron/echno-core`, the TypeScript package the web client uses — the
/// contract comes from the OpenAPI document instead, so drift shows up as a
/// compile error rather than as a runtime surprise. See
/// `local-docs/ios-action-plan.md` §1.
let package = Package(
    name: "EchnoKit",
    platforms: [
        .iOS(.v18),
        // The package is Foundation-only, so it also builds for macOS. That is
        // what lets `swift build` / `swift test` run the logic tests in CI in
        // seconds without booting a simulator. The app itself is iOS-only.
        .macOS(.v14)
    ],
    products: [
        .library(name: "EchnoKit", targets: ["EchnoKit", "EchnoAPI"])
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-openapi-generator", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-openapi-runtime", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-openapi-urlsession", from: "1.0.0")
    ],
    targets: [
        // Generated from the backend's OpenAPI document. Never hand-edited —
        // run `Scripts/sync-openapi.sh` and commit the result.
        //
        // The generator is deliberately NOT attached here as a build-tool
        // plugin. Xcode gates build plugins behind a per-machine trust prompt,
        // and until it is granted the entire scheme fails to build, which takes
        // SwiftUI previews down with it. Generating ahead of time and committing
        // the output means previews, builds and CI work anywhere with no setup.
        .target(
            name: "EchnoAPI",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIURLSession", package: "swift-openapi-urlsession")
            ],
            exclude: [
                "openapi.json",
                "openapi-generator-config.yaml",
                "openapi.source"
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6),
                // The generator emits `public import Foundation` in files that
                // do not need it, which is a warning under Swift 6. They are
                // not ours to fix and there are hundreds; left on, they bury
                // the warnings that are ours.
                .unsafeFlags(["-suppress-warnings"])
            ]
        ),
        .target(
            name: "EchnoKit",
            dependencies: [
                "EchnoAPI",
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIURLSession", package: "swift-openapi-urlsession")
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6)
            ]
        ),
        .testTarget(
            name: "EchnoKitTests",
            dependencies: ["EchnoKit"],
            swiftSettings: [
                .swiftLanguageMode(.v6)
            ]
        )
    ]
)
