#!/usr/bin/env bash
#
# Vendors the backend's OpenAPI document into this repo and normalises it so
# swift-openapi-generator will accept it.
#
# The document is NOT fetched over the network. `springdoc.swagger-ui
# .public-access` defaults to false and the edge vhost 404s the docs paths —
# deliberately, since the document is the entire endpoint surface. The
# committed copy in echno-backend is the source, and the backend's
# OpenApiSnapshotTest fails its build if that copy drifts from what the code
# serves. So vendoring it is as trustworthy as calling the endpoint would be.
#
# Usage:  Scripts/sync-openapi.sh [path-to-echno-backend]

set -euo pipefail

BACKEND="${1:-$(cd "$(dirname "$0")/../.." && pwd)/echno-backend}"
SOURCE="$BACKEND/docs/openapi.json"
DEST_DIR="$(cd "$(dirname "$0")/.." && pwd)/Sources/EchnoAPI"
DEST="$DEST_DIR/openapi.json"
STAMP="$DEST_DIR/openapi.source"

if [[ ! -f "$SOURCE" ]]; then
  echo "error: no OpenAPI document at $SOURCE" >&2
  echo "       pass the echno-backend path as the first argument" >&2
  exit 1
fi

SHA="$(git -C "$BACKEND" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DIRTY=""
if ! git -C "$BACKEND" diff --quiet -- docs/openapi.json 2>/dev/null; then
  DIRTY=" (uncommitted local changes)"
fi

python3 - "$SOURCE" "$DEST" <<'PY'
import json, sys, collections

source, dest = sys.argv[1], sys.argv[2]
doc = json.load(open(source))

# swift-openapi-generator requires root tag names to be unique and refuses the
# whole document otherwise. Six controller pairs declare the same @Tag on both
# the mobile and the web controller where the other 26 suffix the web one with
# "(Web)". Dropping the duplicate declaration unblocks generation; it does NOT
# fix filtering, because the operations still share a tag. Tracked as ask #16 in
# local-docs/backend-mobile-api-gaps.md — delete this block once it lands.
seen, unique, dropped = set(), [], []
for tag in doc.get("tags", []):
    if tag["name"] in seen:
        dropped.append(tag["name"])
        continue
    seen.add(tag["name"])
    unique.append(tag)
doc["tags"] = unique

# ensure_ascii=False matters: the generator parses this JSON with a YAML parser,
# which rejects some \uXXXX escapes that json.dump would otherwise emit.
with open(dest, "w", encoding="utf-8") as handle:
    json.dump(doc, handle, ensure_ascii=False)

ops = sum(1 for methods in doc["paths"].values() for m in methods
          if m in ("get", "post", "put", "patch", "delete"))
print(f"  paths      {len(doc['paths'])}")
print(f"  operations {ops}")
print(f"  schemas    {len(doc.get('components', {}).get('schemas', {}))}")
if dropped:
    print(f"  deduped root tags: {', '.join(sorted(set(dropped)))}")
PY

cat > "$STAMP" <<EOF
# Generated by Scripts/sync-openapi.sh — do not edit.
source   $SOURCE
commit   $SHA$DIRTY
synced   $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo "  source     echno-backend @ $SHA$DIRTY"
echo "synced -> $DEST"
