#!/usr/bin/env bash
#
# Vendors the backend's OpenAPI document and regenerates the Swift client from
# it, writing both into Sources/EchnoAPI/.
#
# The document is NOT fetched over the network. `springdoc.swagger-ui
# .public-access` defaults to false and the edge vhost 404s the docs paths —
# deliberately, since the document is the entire endpoint surface. The committed
# copy in echno-backend is the source, and the backend's OpenApiSnapshotTest
# fails its build if that copy drifts from what the code serves. Vendoring it is
# therefore as trustworthy as calling the endpoint would be.
#
# Generation runs HERE rather than as a build-tool plugin. Xcode gates build
# plugins behind a per-machine trust prompt, and until it is granted the whole
# scheme fails to build — which breaks SwiftUI previews, not just `xcodebuild`.
# Generating ahead of time keeps previews, builds and CI working on any machine
# with no setup, and has the side benefit that a backend contract change arrives
# as a reviewable diff.
#
# Usage:
#   Scripts/sync-openapi.sh [path-to-echno-backend]
#   Scripts/sync-openapi.sh --check [path-to-echno-backend]
#
# --check regenerates into a temporary directory and fails if the committed
# output differs. Run it in CI so a stale client cannot merge.

set -euo pipefail

CHECK=false
if [[ "${1:-}" == "--check" ]]; then
  CHECK=true
  shift
fi

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND="${1:-$(dirname "$REPO")/echno-backend}"
SOURCE="$BACKEND/docs/openapi.json"
API_DIR="$REPO/Sources/EchnoAPI"
DOCUMENT="$API_DIR/openapi.json"
CONFIG="$API_DIR/openapi-generator-config.yaml"
GENERATED="$API_DIR/Generated"
STAMP="$API_DIR/openapi.source"

if [[ ! -f "$SOURCE" ]]; then
  echo "error: no OpenAPI document at $SOURCE" >&2
  echo "       pass the echno-backend path as the first argument" >&2
  exit 1
fi

SHA="$(git -C "$BACKEND" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DIRTY=""
if ! git -C "$BACKEND" diff --quiet -- docs/openapi.json 2>/dev/null; then
  DIRTY=" (uncommitted local changes)"
fi

normalise() {
  python3 - "$SOURCE" "$1" <<'PY'
import json, sys

source, dest = sys.argv[1], sys.argv[2]
doc = json.load(open(source))

# swift-openapi-generator requires root tag names to be unique and refuses the
# whole document otherwise. Six controller pairs declare the same @Tag on both
# the mobile and the web controller where the other 26 suffix the web one with
# "(Web)". Dropping the duplicate declaration unblocks generation; it does NOT
# fix filtering, because the operations still share a tag. Tracked as ask #16 in
# local-docs/backend-mobile-api-gaps.md — delete this block once it lands.
seen, unique, dropped = set(), [], []
for tag in doc.get("tags", []):
    if tag["name"] in seen:
        dropped.append(tag["name"])
        continue
    seen.add(tag["name"])
    unique.append(tag)
doc["tags"] = unique

# ensure_ascii=False matters: the generator parses this JSON with a YAML parser,
# which rejects some \uXXXX escapes that json.dump would otherwise emit.
with open(dest, "w", encoding="utf-8") as handle:
    json.dump(doc, handle, ensure_ascii=False)

ops = sum(1 for methods in doc["paths"].values() for m in methods
          if m in ("get", "post", "put", "patch", "delete"))
print(f"  paths      {len(doc['paths'])}")
print(f"  operations {ops}")
print(f"  schemas    {len(doc.get('components', {}).get('schemas', {}))}")
if dropped:
    print(f"  deduped root tags: {', '.join(sorted(set(dropped)))}")
PY
}

# The generator narrates its whole configuration to stdout and stderr on every
# run. Captured and replayed only on failure, so a successful sync stays quiet
# and a failed one still shows why.
generate() {
  local document="$1" output="$2" log
  log="$(mktemp)"
  mkdir -p "$output"
  if ! swift run --package-path "$REPO" swift-openapi-generator generate \
       "$document" --config "$CONFIG" --output-directory "$output" >"$log" 2>&1; then
    echo "error: generation failed" >&2
    cat "$log" >&2
    rm -f "$log"
    return 1
  fi
  rm -f "$log"
}

if [[ "$CHECK" == true ]]; then
  TEMP="$(mktemp -d)"
  trap 'rm -rf "$TEMP"' EXIT
  normalise "$TEMP/openapi.json" >/dev/null
  generate "$TEMP/openapi.json" "$TEMP/Generated"
  if diff -rq "$GENERATED" "$TEMP/Generated" >/dev/null 2>&1 \
     && diff -q "$DOCUMENT" "$TEMP/openapi.json" >/dev/null 2>&1; then
    echo "OpenAPI client is up to date with echno-backend @ $SHA"
    exit 0
  fi
  echo "error: the generated client is stale." >&2
  echo "       run Scripts/sync-openapi.sh and commit the result." >&2
  diff -rq "$GENERATED" "$TEMP/Generated" 2>&1 | sed 's/^/       /' >&2 || true
  exit 1
fi

echo "Vendoring the OpenAPI document…"
normalise "$DOCUMENT"

echo "Generating the Swift client…"
rm -rf "$GENERATED"
generate "$DOCUMENT" "$GENERATED"
echo "  $(find "$GENERATED" -name '*.swift' | wc -l | tr -d ' ') files, \
$(find "$GENERATED" -name '*.swift' -exec cat {} + | wc -l | tr -d ' ') lines"

cat > "$STAMP" <<EOF
# Generated by Scripts/sync-openapi.sh — do not edit.
source   $SOURCE
commit   $SHA$DIRTY
synced   $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo "  source     echno-backend @ $SHA$DIRTY"
echo "Done. Commit Sources/EchnoAPI/ so every machine builds without setup."
